{{cookiecutter.app_name}}/{{cookiecutter.package_name}}/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

{{cookiecutter.app_name}}/{{cookiecutter.package_name}}/main/views.py
# -*- coding: utf-8 -*-
"""Views for the main package of {{cookiecutter.app_name}}

.. module:: views
    :platform: Unix
    :synopsis: Views for the main package.
.. moduleauthor:: {{cookiecutter.author_name}} <{{cookiecutter.email}}>
"""
from flask import render_template
from . import main

@main.route('/')
def index():
    return render_template('index.html')

@main.route('/about')
def about():
    return render_template('about.html')

{{cookiecutter.app_name}}/{{cookiecutter.package_name}}/templates/about.html
{% raw %}
{% extends "base.html" %}
{% block page_content %}
{% endraw %}
<h1>About {{cookiecutter.app_title}}</h1>
<p>{{cookiecutter.description}}. {{cookiecutter.app_title}} is open source and
    available on <a href=
        "https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.app_name}}/">
        GitHub</a>
</p>
{% raw %}
{% endblock %}
{% endraw %}

{{cookiecutter.app_name}}/{{cookiecutter.package_name}}/templates/base.html
{% raw %}
{% extends "bootstrap/base.html" %}

{% block styles %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
{% endblock %}

{% block title %}
{% endraw %}
{{cookiecutter.app_title}}
{% raw %}
{% endblock %}

{% block navbar %}
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                data-target="#mainNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href={{ url_for('main.index') }}>{% endraw %}{{cookiecutter.app_title}}{% raw %}</a>
        </div>
        <div class="collapse navbar-collapse" id="mainNavbar">
            <ul class="nav navbar-nav">
                <li class="active"><a href={{ url_for('main.index') }}>Home</a></li>
                <li><a href={{ url_for('main.about') }}>About</a></li>
            </ul>
        </div>
    </div>
</nav>
{% endblock %}

{% block content %}
<div class='container'>
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close"
            data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}
    {% block page_content %}{% endblock %}
</div>
<footer>
    <div class="container">
        {% endraw %}
        {{cookiecutter.author_name}} &copy; 2017, <a href=
            "https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.app_name}}/blob/master/LICENSE">
            MIT License</a>
        {% raw %}
    </div>
</footer>
{% endblock %}
{% endraw %}

{{cookiecutter.app_name}}/{{cookiecutter.package_name}}/templates/index.html
{% raw %}
{% extends "base.html" %}
{% block page_content %}
{% endraw %}
<h1>{{cookiecutter.app_name}} lives!</h1>
{% raw %}
{% endblock %}
{% endraw %}